### ISSUE TITLE
How to handle time periods extracting daily chirps data with rerddap

### ISSUE THREAD

**Issue by jordi-1** [ropensci/rerddap#117] opened 2024-10-28 18:19 UTC
I'm trying to download chirps daily rainfall data, but I can't seem to predict what time range will be downloaded depending on the dates I input in the griddap() instructions. Any guidance ? 

```r

pacman::p_load(
  tidyverse,
  lubridate,
  
  sf, 
  terra,
  
  rerddap,
  ncdf4)

rm(list=ls())


cache_setup(full_path = "chirps_data")
cache_delete_all()

cache_list()

# e_servers <- "https://coastwatch.pfeg.noaa.gov/erddap/"
# test_query <- 'CHIRPS'
# query_results <- global_search(test_query, e_servers, "griddap")


dataInfo <- rerddap::info('chirps20GlobalDailyP05')

 lon_range= c(4.5, 5.5)
 lat_range=c(8.5, 9.5)


res<-griddap(dataInfo, fmt="nc", 
              store=disk(overwrite = TRUE),
              latitude = lat_range, 
              longitude = lon_range, 
              time = c('2012-12-31', '2018-01-01'), 
              fields = 'all',
              read=FALSE)

chirps_cube=rast(res$summary$filename) 

date_obs=time(chirps_cube) %>% as_date()

min(date_obs)
max(date_obs)

### run number 1 : time period requested : from 31 dec 2012 to 1 jan 2018 
### period downloaded : from 31 dec 2012 to 1 jan 2019


res2<-griddap(dataInfo, fmt="nc", 
             store=disk(overwrite = TRUE),
             latitude = lat_range, 
             longitude = lon_range, 
             time = c('1990-01-01', '2000-01-01'), 
             fields = 'all',
             read=FALSE)

chirps_cube2=rast(res2$summary$filename) 

date_obs2=time(chirps_cube2) %>% as_date()

min(date_obs2)
max(date_obs2)

### run number 2: time period requested : from 1 jan 1990 to 1 jan 2000 
### period downloaded : from 31 dec 2012 to 1 jan 2000
```

<details> <summary><strong>Session Info</strong></summary>

─ Session info ────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.2 (2023-10-31 ucrt)
 os       Windows 11 x64 (build 22631)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  French_France.utf8
 ctype    French_France.utf8
 tz       Atlantic/Reykjavik
 date     2024-10-28
 rstudio  2024.09.0+375 Cranberry Hibiscus (desktop)
 pandoc   NA

**Comment by rmendels** [comment] 2024-10-28 19:05
@jordi-1   Thanks for your comment.  The answer is there are problems with the CHIRPS datasets,  it is on my to-do list to try and figure out.  You can see the problem by looking at:

https://coastwatch.pfeg.noaa.gov/erddap/griddap/chirps20GlobalDailyP05.htmlTable?time%5B(2012-12-31):1:(2018-01-01)%5D


There is no data for the the time period 2017-2018 (among other missing time periods).  So why does 1 jan 2019 get pulled down?  Because for 1 jan 2018 there is data later than that date,  and 1 jan 2019 is the "closest" to that date.  It is about what do you do when the  bounding box values are not in the actual dimensions values.  ERDDAP will map the end points to the "nearest" actual values and then extract for all values in between.  So ERDDAP (and rerddap) are doing the "correct" thing,  the problem is with the dataset.  I am not very familiar with the CHIRPS data,  will have to look to see what is happening,  please understand that we a very small group,  understaffed and underfunded,  so it may be a bit before I get to this.  I will let you know if and when I think the issue is resolved.

**Comment by rmendels** [comment] 2024-10-28 20:04
@jordi-1   Try now (luckily this was relatively easy to fix).  There were some bad files.  Each year is one file,  so  if the file is bad the whole year is lost.  If you run into other problems with CHIRPS data please let me know  (even though this is for rerddap we also run that ERDDAP. It is just not a dataset that we monitor often.

**Comment by jordi-1** [comment] 2024-10-29 07:26
Hi Roy,
Thanks for the feedback. I'm actually used to working a lot with CHIRPS which provides one of the highest resolution datasets worldwide (I work on malaria epidemiology, which involves study settings in Africa and Asia). 

Many thanks for your efforts to provide the data and an access under a stable and opensource format. As far as I can tell from relying extensively on CHIRPS (previously accessed with EE), the dataset is a complete series since 1980. Let me know if there's something I can do regarding gaps. If useful, I could start with a couple of locations and try to see if there are other gaps, before reporting them to you. 

Thanks again !

**Comment by rmendels** [comment] 2024-10-29 14:15
@jordi-1 I believe the problem is fixed and there should not be any gaps,  and while I have done some checks they were not extensive.  And while the data may be high quality people often are mistakes  creating netcdf flles,  and ERDDAP is to forgiving - that is there is no sort of correct.

I would add that your code above has an error,  what you need is:

```r
myURL <- 'https://coastwatch.pfeg.noaa.gov/erddap/'
dataInfo <- rerddap::info('chirps20GlobalDailyP05', url = myURL)
```

I am going to close this but if you find other problems re-open this and let me know.  The main thing is it is not an rerddap error

**Closed by rmendels** 2024-10-29 14:15 UTC
