### ISSUE TITLE
ROMS data doens't work correctly

### ISSUE THREAD

**Issue by sckott** [ropensci/rerddap#44] opened 2016-04-06 20:31 UTC
``` r
library(rerddap)
testInfo<-info('glos_tds_976e_41ad_58ec')

dimargs <- list(ny=c(31,33), nx=c(150,152))

##  this fails
extract<-griddap(x = testInfo, ny=c(31,33), nx=c(150,152))

## this works
extract<-griddap(testInfo,ny=c(31,33), nx=c(150,152), read=FALSE)

#The first fails because in “melting” the grid to “long-form” the code explicitly assumes 
# latitude and longitude.  Or as another example, extracting from a ROMS model:
testInfo <- info('whoi_f2e9_92f8_cca9')

### this fails
extract <- griddap(testInfo,time=c('2007-09-06','2007-09-06'), 
                   eta_rho=c(0,2),xi_rho=c(20,22), fields='bestrew')
### this works
extract <- griddap(testInfo,time=c('2007-09-06','2007-09-06'), 
                   eta_rho=c(0,2),xi_rho=c(20,22), fields='bestrew', read=FALSE)

# I am pretty certain the dimension checks won’t work correctly should 
# I give one out of the actual range, because those also, to the best 
# I can tell from looking at the code, specific to lat-lon-time.
```

**Comment by richardsc** [comment] 2018-01-30 03:20
I think I am seeing this same issue related to the recent Salish Sea ERDDAP server (PR #69), as the dimensions are defined as: `time`, `depth`, `gridX`, `gridY`. When I run an example code I get a `data.frame` error about different numbers of rows:

```r
library(rerddap)

url <- "https://salishsea.eos.ubc.ca/erddap/"
d <- ed_datasets(url=url, which='griddap')
out <- info(d$Dataset.ID[18], url=url)

res <- griddap(out, fields='nitrate', url=url,
               time=c('2014-10-16', '2014-10-22'),
               gridY=c(505, 510),
               gridX=c(204, 216))
```
This code fails with:
```
Error in data.frame(time, lat, lon, stringsAsFactors = FALSE) : 
  arguments imply differing number of rows: 452400, 0
```
but as with your examples I can make the error go away by setting `read=FALSE`.

Is there a fix for this? As far as I can tell from looking at 979c70c the code still depends explicitly on having `lon` and `lat` present

**Comment by sckott** [comment] 2018-01-31 00:13
thanks for the report. 

can you share your session info?

**Comment by sckott** [comment] 2018-01-31 00:22
one way to do this could be to use https://github.com/hypertidy/tidync from @mdsumner 

e.g., 

```r
library(rerddap)
devtools::install_github("hypertidy/tidync")
library(tidync)

url <- "https://salishsea.eos.ubc.ca/erddap/"
d <- ed_datasets(url=url, which='griddap')
out <- info(d$Dataset.ID[18], url=url)

res <- griddap(out, fields='nitrate', url=url,
               time=c('2014-10-16', '2014-10-22'),
               gridY=c(505, 510),
               gridX=c(204, 216), read = FALSE)
file <- attributes(res)$path
z <- tidync::tidync(file)
z
```

```r
#> Data Source (1): ebfe27198a7284e3e445f56b45f9fce0.nc ...
#> 
#> Grids (5) <dimension family> : <associated variables>
#> 
#> [1]   D3,D2,D1,D0 : nitrate    **ACTIVE GRID** ( 452400  values per variable)
#> [2]   D0          : time
#> [3]   D1          : depth
#> [4]   D2          : gridY
#> [5]   D3          : gridX
#> 
#> Dimensions (4):
#> 
#>   dimension    id name  length unlim coord_dim active start count
#>   <chr>     <dbl> <chr>  <dbl> <lgl> <lgl>     <lgl>  <int> <int>
#> 1 D0         0    time  145    F     T         T          1   145
#> 2 D1         1.00 depth  40.0  F     T         T          1    40
#> 3 D2         2.00 gridY   6.00 F     T         T          1     6
#> 4 D3         3.00 gridX  13.0  F     T         T          1    13
```

**Comment by richardsc** [comment] 2018-01-31 00:52
Sorry, here's my `sessionInfo()`:
```
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rerddap_0.4.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14        digest_0.6.12       dplyr_0.7.4         assertthat_0.2.0    hoardr_0.2.0       
 [6] rappdirs_0.3.1      R6_2.2.1            jsonlite_1.4        magrittr_1.5        ncdf4_1.16         
[11] httr_1.3.1          rlang_0.1.4         curl_2.8.1          data.table_1.10.4-3 bindrcpp_0.2       
[16] xml2_1.1.1          tools_3.4.2         glue_1.2.0          compiler_3.4.2      pkgconfig_2.0.1    
[21] bindr_0.1           tibble_1.3.4   
```

Reading the nc file that is downloaded isn't an issue (though I didn't know about `tidync`, thanks!), as it can be done directly with the `ncdf4` package outside of the `griddap()` call, but of course it doesn't provide a consistent interface to the data.

**Comment by sckott** [comment] 2018-01-31 01:02
Thanks for that. 

Right, a consistent interface is the point here - one reason I suggested maybe `tidync` is that I don't know enough about ERDDAP or netcdf to make sure that I have a robust solution to parsing netcdf file data. So one solution could be to use tidync to read it in - then reshape it into the current format we use, or something better . 

thoughts?

**Comment by mdsumner** [comment] 2018-01-31 01:22
I'm happy to help guide use of tidync for this!  One thing that might work is to pass the rerddap ready structure, with gridX/gridY renamed to lon/lat, but generally and likely here (because ROMS) - the gridX/gridY might be index steps, or actual easting/northing in some crs.  (My ROMS explorations are in [angstroms](https://cran.r-project.org/package=angstroms) - not yet aligned to tidync. )

If you use ncdf4 or RNetCDF the interface will be consistent, though only RNetCDF on Windows will support remote calls at the moment. 

tidync uses RNetCDF for this reason, so it's cross-platform and can deal with files or remote sources - and I find RNetCDF a bit cleaner, although ncdf4 is faster because of some unnecessary duplication in RNetCDF. 

I saw this today, which is a perfect description of the problem, NetCDF is not a "format". :)  

https://twitter.com/TedHabermann/status/958034585002041344

**Comment by mdsumner** [comment] 2018-01-31 04:20
Also, I think we've been talking across each other a bit @sckott (please forgive me if my take is off). To me what's missing from NetCDF/online-sources is the *catalog* system, because ultimately if you have a *file-path analog* to a source, you can use ncdf4, raster, RNetCDF, rgdal, anything that is NetCDF+Thredds capable. It seems rerddap has a lot of smarts for trawling a source url, and understanding what's there - but then it passes over to actually download a file - whereas we need a level just below that, so a user can identify a variable at a source, then start issuing subsetting read queries. 

Anyway, that's my thoughts for now, I had a quick look and I think I understand what ERDDAP is better now :) 

It's the OpenDAP libraries URL that we need for the generic calls. I can't see how to structure them right for GDAL, though that might be my system GDAL (either DODS driver missing, or clashing with the HTTP driver). It won't work for raster because it triggers use of ncdf4 only by detecting ".nc" in the url  (or similar). 

```R
library(rerddap)
#devtools::install_github("hypertidy/tidync")
library(tidync)

url <- "https://salishsea.eos.ubc.ca/erddap/"
d <- ed_datasets(url=url, which='griddap')
out <- info(d$Dataset.ID[18], url=url)

## digging under hood of griddap()...
x <- rerddap:::as.info(out, url)
d <- attr(out, "datasetid")
## https://salishsea.eos.ubc.ca/erddap/griddap/documentation.html#fileType
## under OpenDap libraries
# When creating the initial connection to an ERDDAP griddap dataset from any OPeNDAP library:
#   
#   Don't include a file extension (e.g., .nc) at the end of the dataset's name.
# Don't specify a variable or a subset of the dataset.

source_nc <- sprintf("%sgriddap/%s", url, d)

## so now we have all good for
RNetCDF::open.nc(source_nc)
ncdf4::nc_open(source_nc)
tidync(source_nc)

## but
##raster::raster(source_nc)  ## no
##rgdal::GDAL.open(source_nc)  ## no

```

**Comment by mdsumner** [comment] 2018-01-31 05:10
fwiw, here's my exploration of the grid data with tidync, I don't think it easily solves anything but we might be able to leverage some of the lessons together ... tidync makes it easy to pass those raw subset expressions down, and get out a tibble (or arrays with hyper_slice) that has everything expanded out - but any interpretation (like time) is avoided. For ERDDAP sources, and other more reliable sources tidync *could* provide a time (and other units) interpretation. I'd like to explore a tidync/ggplot wrapper on rerddap to explore what's available, and that might be worth pursuing - but I think our ultimate outputs are generally similar. 

http://rpubs.com/cyclemumner/354372

**Comment by rmendels** [comment] 2018-02-05 23:55
rerddap should work with the ROMS data if you tell it not to read into memory,  instead to get the file and then read in the file yourself.  That would mean if you put in the formals  "read = FALSE"  and use the "store" argument to pass where you want the file stored. The problem as Scott suggested above is when "read = TRUE" rerddap "melts" the data assuming there lat-lon exist.  

I would add the ERDDAP can act as a regular OpeNDAP server,  so if there are other programs that can do OpeNDAP access,  they will work with ERDDAP.

-Roy

**Comment by sckott** [comment] 2018-02-09 18:32
right @rmendels a user can just set `read=FALSE`, but I think we should make it so that users can read data without having to know the detailsl of how to do it. 

Thanks for all that @mdsumner  - how do you recommend we move forward?

**Comment by rmendels** [comment] 2018-02-09 18:53
@sckott @mdsumner 

I think when you first were working on rerddap (though I may be confused) I suggested for griddap() something like testing if lat-lon were part of the coordinate system,  and only melt in that case.  If not,  read in the .csv or .nc file as an array.

Or melt but don't melt by assuming that the coordinate system is lat-lon, and don't assume the coordinate system is 2-D.  I believe the original idea was to melt for mapping,  but there area lot of data in ERDDAPs around the world not on lat-lon grids - mainly model output). The coordinates should have names,  and this should be doable,  but that is easy for me to say as I won't have to figure out how.  I installed tidync and related code awhile back  (I have been away from work the last few weeks so only working now and then) - but if I remember correctly @mdsumner  already has code either in tidync or in tabularaster that does this or something close to this.  

The more I think about it the more I prefer the latter solution,   if you are going to melt,  make the melt more general.  And as I said,  @mdsumner may already have code that pretty much does this.

-Roy

**Comment by sckott** [comment] 2018-02-12 22:45
thanks @rmendels

**Comment by rmendels** [comment] 2018-02-13 17:09
@sckott

I was just re-reading this thread again.  I don't think the issue is what you are using to read in the netcdf file,  all the information you need is available from ncdf4 say.  In rerddapXtracto I read in data from netcdf files using ncdf4 and not assuming lat-lon, and it works fine - but then again I am not then "melting" the data.  If it is a griddap() call,  I know there will always be at least 2-dimensions,  and possibly up to 4.  So it is an issue of finding the number of dimensions returned,  and the dimension names, and being careful when reading using ncdf4 not to have it automatically "squeeze" an array with a dimension of size 1.

The issue is purely in the melting step.  If using tidync makes it easier to do that step,  go for it.  But looking at the rerddap code at the moment,  the code you have now is basically doing what you need except that you assume lat-lon dimensions,  rather than arbitrary dimensions,  and you assume at most 3 dimensions, when there may be 4.

Also wondering if either reshape2::melt() or tidy::gather() might already do what you want.  

Mainly just trying to keep it simple.  Some of the things suggested above I think would make the code much more difficult.

-Roy

**Comment by mdsumner** [comment] 2018-02-13 21:28
It doesn't have to "melt" by default, hyper_slice will pull out raw arrays and the (selected) axis coordinate values are already present in the tidync object. I just find these idioms aren't well worked out or understood, so not sure how to present them. Always happy to explore concrete examples and code.

**Comment by rmendels** [comment] 2018-02-19 22:12
@sckott 

I was looking over your code again to see if reshape2::melt() might already melt the arrays returned in a netcdf file,  so I looked to see how you are reading in the netcdf files.  Looking at the function ncdf4_get().  See this section:

```{r}
  if (length(out$time) == 0) {
    out$time <- NULL
    exout <- do.call("expand.grid", out)
    meta <- dplyr::arrange_(exout, names(exout)[1])
  } else {
    time <- suppressWarnings(rep(out$time, each = rows/length(out$time)))
    lat <- rep(rep(out$latitude, each = length(out$longitude)),
               length(out$time))
    lon <- rep(rep(out$longitude, times = length(out$latitude)),
               times = length(out$time))
    meta <- data.frame(time, lat, lon, stringsAsFactors = FALSE)
  }
```

So you are assuming the coordinate system, and this will fail for data like the ROMS data.  Again,  whether you use ncdf4,  or tidync,  the coordinate system is available,  in ncdf4 on the initial ncdf4::nc_open() call.   

I am going to play around with reshape2::melt() with some netcdf files I have.  Will let you know what I find.

-Roy

**Comment by mdsumner** [comment] 2018-02-20 05:05
tidync's dimensionally agnostic "melt"  is here:

https://github.com/hypertidy/tidync/blob/master/R/hyper_tibble.R

This convo is making me think there's room for a stripped down version to wrap ncdf4 and RNetCDF just for this. It's slice-lazy,  but not DBI-lazy but I've been exploring that - I think it needs merely to show the head and require a collect(),  which I think now is worth doing standalone.

**Comment by rmendels** [comment] 2018-02-20 18:24
@sckott @mdsumner 

So I took a "well_behaved"  netcdf file  (that is with a lat-lon coordinate system) and did the following two tests:

1.  Read the file in using rerddap:::ncdf4_get, and then used reshape2::melt().

2.  Read the file in using tidync::tidying() and then used tidync::hyper_tibble()

For the former,  to get the result desired,  I had to identify the "id" columns,  and it produced the following:

```{r}
# junk is the result of reading the file using ncdf4_get()
junk1 <- melt(junk$data, id = c("time", "lat, "lon"))
str(junk1)
'data.frame':	242406 obs. of  5 variables:
 $ time    : chr  "2006-01-15T00:00:00Z" "2006-01-15T00:00:00Z" "2006-01-15T00:00:00Z" "2006-01-15T00:00:00Z" ...
 $ lat     : num  40 40 40 40 40 40 40 40 40 40 ...
 $ lon     : num  230 230 230 230 230 ...
 $ variable: Factor w/ 1 level "sst": 1 1 1 1 1 1 1 1 1 1 ...
 $ value   : num  12.4 12.4 12.3 11.9 11.8 ...
```

Using tidync:

```{r}
 rnc <- tidync('sst_1.nc')
ht <- hyper_tibble(rnc)
str(ht)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	232345 obs. of  5 variables:
 $ sst      : num  12.4 12.4 12.3 11.9 11.8 ...
 $ longitude: num  230 230 230 230 230 ...
 $ latitude : num  40 40 40 40 40 40 40 40 40 40 ...
 $ altitude : num  0 0 0 0 0 0 0 0 0 0 ...
 $ time     : num  1.14e+09 1.14e+09 1.14e+09 1.14e+09 1.14e+09 ...
```

tidync certainly is easier and requires less knowledge of the structure of the netcdf file in order to "melt" the data.  I still have to test both with a "non-standard" coordinate system like in the ROMS file,  will let you know.   Downside of tidync is not on CRAN yet  (any ETA?) and requires both ncdf4 and RNetCDF.

**Comment by rmendels** [comment] 2018-02-20 18:40
@sckott @mdsumner 
Okay I used the example in the comment above that re-opened this issue.

```{r}
library(rerddap)

url <- "https://salishsea.eos.ubc.ca/erddap/"
d <- ed_datasets(url=url, which='griddap')
out <- info(d$Dataset.ID[18], url=url)

res <- griddap(out, fields='nitrate', url=url,
               time=c('2014-10-16', '2014-10-22'),
               gridY=c(505, 510),
               gridX=c(204, 216), read = FALSE)
# moved the cached netcdf file to "roms.nc"
rnc <- tidync('roms.nc')
ht <- hyper_tibble(rnc)
str(ht)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	452400 obs. of  5 variables:
 $ nitrate: num  11.6 11 11 11.2 10.5 ...
 $ gridX  : num  204 205 206 207 208 209 210 211 212 213 ...
 $ gridY  : num  505 505 505 505 505 505 505 505 505 505 ...
 $ depth  : num  0.5 0.5 0.5 0.5 0.5 ...
 $ time   : num  1.41e+09 1.41e+09 1.41e+09 1.41e+09 1.41e+09 ...
```
This is correct, and would certainly seem to be the easiest solution if you want to  "melt" the result  of the griddap() call and not have to worry too much about the structure of what you downloaded.  Probably the only other step would be to test if "time" was a coordinate and convert from a udunits type time to an R time.

**Comment by mdsumner** [comment] 2018-02-22 07:45
Thanks @rmendels!  tidync still needs a bit before CRAN, I've been exploring lazy_ops in dplyr and that looks like a very promising way to "hyper_tibble", without actually pulling any data - until an explicit collect(). I need to explore that a bit more before reviewing some final changes to tidync.  It's definitely a few weeks or more, though I do think it's worth releasing without any lazy stuff. 

The real power of `tidync() .. something something ... hyper_tibble()` is that you can put hyper_filter() expressions in there so the final result is only the melt of a slice, but it does imply some interactive exploration by the user. There should be no need to download a file if it's not local already. 

Do you think ncdf4+RNetCDF is really a problem? I think I can remove ncdf4, and that's preferable because only RNetCDF will handle Thredds on Windows (only 64-bit though). 

I really appreciate this discussion, I know there's a lot of room for improvement here!  I'm starting to see tidync as an extended learning process for me, I think it can be much better (with dplyr lazy_ops).

**Comment by rmendels** [comment] 2018-02-24 17:14
@mdsumner @sckott 

I have been trying to keep my comments relevant to the issues @sckott  faces in order to read in and "melt" netcdf files  in rerddap without assuming lat-lon coordinates  So I will keep it brief here,  can move other things over to tidync if desired.

At one point or another,  both ncdf4 and RNetCDF have lagged either netcdf development of R development,  across platforms - this was exacerbated by CRAN not having the netcdf4 libraries on their Windows machines and not accepting binaries, a Catch-22.  I also am not certain how much longer David Pierce will be supporting ncdf4 development, which is important since netcdf files are de rigeur in certain communities.  IMHO,  the more things you rely on the more chances you face something not working as things evolve,  particularly since these packages depend on external libraries.

As for tidync,  I still have not had much of a chance to really read through the docs and play with it.  I will say I look at things that are gaining traction in the community,  and on the Python side it is the Xarray package,  you might look at some of their design.  They are designing to be "pandas" like,  and CF-like,   while you are designing for the tidyverse,  so there will clearly be differences,  and some of their features are most likely for long-term development in tidync, it would be nice to have the package on CRAN with basically the feature set it has at present.   Also for ERDDAP,  there is the Python package erddapy,  in fact inspired by rerddap.

**Comment by mdsumner** [comment] 2018-02-24 22:43
I agree we are lagging, and I agree this is super-important - I'm amazed how little attention NetCDF gets in R still. Apologies @sckott for continuing to hijack here, but I don't mind where we discuss, happy to take it anywhere.  The situation is much better than it was, with RNetCDF now built for version 4 on Windows with Thredds support, rgdal now includes it on Windows. 

I've tried to stimulate discussion here: https://github.com/RConsortium/wishlist/issues/3  

I've started a barebones rewrite here https://github.com/hypertidy/ncapi but, I'm mostly out of my depth with C++.

**Closed** 2022-05-27 21:33 UTC
Labels: bug
